import pandas as pd
import numpy as np
import json
import os
from pprint import pprint
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
plt.style.use('bmh')
plt.rcParams['axes.facecolor'] = '#eaeaf2'  # light bluish-gray
plt.rcParams['grid.color'] = 'white'
plt.rcParams['grid.linewidth'] = 1.2         # make grid lines thicker
plt.rcParams['grid.linestyle'] = '-'         # solid grid lines
import seaborn as sns
import math
import scipy.stats as stats
from scipy.stats import binomtest, pearsonr, gaussian_kde
from statsmodels.stats.multitest import multipletests
from scipy.spatial.distance import jensenshannon
from sklearn.decomposition import PCA
from statsmodels.stats.multitest import multipletests
from sklearn.manifold import Isomap

# - - - MAIN ANALYSIS - - -
def labels_mean_scores(df):
    ''' Calculates mean and std of 4-AFC responses in Experiment 1. Moreover, conducts binomial tests to assess recognition accuracy. 
    '''
    participants = [col for col in df.columns if 'L' in col]
    conditions = df['condition'].unique()
    actors = df['actor'].unique()

    #Calculate means per condition
    condition_means_df = {}
    for condition in conditions:
        condition_df = df[df['condition'] == condition]
        xs = condition_df[participants].values.reshape(-1,)
        #Since we're missing one stimuli in two actors...
        k = np.nansum(xs)
        n = xs.shape[0] if not np.isnan(list(xs)).any() else xs.shape[0]-1
        #print(xs.shape[0])
        p_val = round(binomtest(k, n, p=0.25, alternative='greater').pvalue, 4)
        mean = np.nanmean(xs)
        #In order not to artificially inflating sample size, divide by num of participants NOT by num of responses (n)
        std = np.array(np.sqrt(mean * (1 - mean) / len(participants)))
        condition_means_df[condition] = [mean, std, p_val]
    condition_means_df = pd.DataFrame(condition_means_df).T
    condition_means_df.columns = ['MEAN', 'STD', 'pval']

    #Calculate means per actor
    actor_means_df = {}
    for actor in actors:
        actor_df = df[df['actor'] == actor]
        xs = actor_df[participants].values.reshape(-1,)
        #Since we're missing one stimuli in two actors...
        k = np.nansum(xs)
        n = xs.shape[0] if not np.isnan(list(xs)).any() else xs.shape[0]-1
     #   print(n)
        p_val = round(binomtest(k, n, p=0.25, alternative='greater').pvalue, 4)
        mean = np.nanmean(xs)
        #In order not to artificially inflating sample size, divide by num of participants NOT by num of responses (n)
        std = np.array(np.sqrt(mean * (1 - mean) / len(participants)))
        actor_means_df[actor] = [mean, std, p_val]
    actor_means_df = pd.DataFrame(actor_means_df).T
    actor_means_df.columns = ['MEAN', 'STD', 'pval']
    return condition_means_df, actor_means_df

def grid_mean_scores(df):
    ''' Calculates mean and std of valence x arousal responses in Experiment 2.
    '''
    participants = [col for col in df.columns if 'G' in col]
    conditions = df['condition'].unique()
    actors = df['actor'].unique()
    #Calculate means per condition
    condition_means_df = {}
    for condition in conditions:
        condition_df = df[df['condition'] == condition]
        xs = condition_df[participants].values.reshape(-1,)
        mean = np.nanmean(xs)
        std = np.nanstd(xs)
        condition_means_df[condition] = [mean, std]
    condition_means_df = pd.DataFrame(condition_means_df).T
    condition_means_df.columns = ['MEAN', 'STD']

    #Calculate means per actor
    actor_means_df = {}
    for actor in actors:
        actor_df = df[df['actor'] == actor]
        xs = actor_df[participants].values.reshape(-1,)
        mean = np.nanmean(xs)
        std = np.nanstd(xs)
        actor_means_df[actor] = [mean, std]
    actor_means_df = pd.DataFrame(actor_means_df).T
    actor_means_df.columns = ['MEAN', 'STD']
    return condition_means_df, actor_means_df

def compute_jsd(density_array, base=2):
    """
    Computes the average pairwise Jensen-Shannon divergence between a set of 2D densities.
    (Generated by ChatGPT)
    """
    n = density_array.shape[0]
    flat_densities = []

    # Flatten and normalize each distribution
    for i in range(n):
        p = density_array[i].ravel()
        p = np.clip(p, 1e-10, None)  # avoid log(0)
        p /= p.sum()  # normalize to sum to 1
        flat_densities.append(p)
    
    # Compute all pairwise JSDs
    jsd_vals = []
    for i in range(n):
        for j in range(i + 1, n):
            jsd = jensenshannon(flat_densities[i], flat_densities[j], base=base)**2
            jsd_vals.append(jsd)
    
    return np.mean(jsd_vals)

def JSD_analysisNplots(grid_df, grid_val_df, grid_aro_df, r_mean_df, save_figs = True):
    # Check if data is already saved
    JSD_data_path = 'final_datafiles/JSD_dict.json'
    if os.path.isfile(JSD_data_path):
        # Only skip function if we don't need to plot
        if not save_figs:
            with open(JSD_data_path) as JSD_dict:
                return json.load(JSD_dict)

    #Get needed data
    all_grid_val_df = grid_df[grid_df['variable'] == 'val']
    all_grid_aro_df = grid_df[grid_df['variable'] == 'aro']
    actors = np.sort(all_grid_aro_df['actor'].unique())
    participants = [col for col in all_grid_aro_df.columns if 'G' in col]
    participants.sort()
    conditions = list(np.unique(all_grid_val_df['condition']))
    JSD_dict = {}

    #Prepare meshgrid needed for JSD
    x = np.linspace(-150, 150, 300)
    y = np.linspace(0, 300, 300)
    X, Y = np.meshgrid(x, y)
    positions = np.vstack([X.ravel(), Y.ravel()])

    #For each condition...
    for condition in conditions:
        cond_val_df = all_grid_val_df[all_grid_val_df['condition'] == condition]
        cond_aro_df = all_grid_aro_df[all_grid_aro_df['condition'] == condition]
        if save_figs:
            fig, ax = plt.subplots(3,5,figsize=(8.1,6))

        #...get grid data distributions for all actors
        all_cond_distributions = []
        all_r_means = []
        for actor_idx,actor in enumerate(np.append(['All means'], actors)):
            
            actor_cond_val_df = cond_val_df[cond_val_df['actor'] == actor]
            actor_cond_aro_df = cond_aro_df[cond_aro_df['actor'] == actor]
            if save_figs:
                curr_ax = ax[int(actor_idx / 5)][actor_idx % 5]
            if actor == 'All means':
                if save_figs:
                    curr_ax.scatter(grid_val_df[actors].loc[condition], grid_aro_df[actors].loc[condition], color='indianred', alpha=0.6, s=5)
                    curr_ax.scatter(grid_val_df['MEAN'].loc[condition], grid_aro_df['MEAN'].loc[condition], color='red', s=9)
            elif not ((actor == 'F6' and condition == 'Concerned') or (actor == 'F7' and condition == 'Nervous')):
                #...calculate JSD
                xs = actor_cond_val_df[participants]
                ys = actor_cond_aro_df[participants] + 150
                kde = gaussian_kde([xs.values[0], ys.values[0]])
                all_cond_distributions.append(kde(positions).reshape(X.shape))
                r_mean = r_mean_df[actor][condition]
                all_r_means.append(r_mean) #maybe not needed
                if save_figs: 
                    if actor != 'All means':
                        # Plot a countous according to the kde
                        kde = gaussian_kde([xs.values[0], ys.values[0]])
                        kde_vals = kde(positions).reshape(X.shape)
                        curr_ax.contourf(X, Y, kde_vals, levels=15, cmap='Greens', alpha=0.3, zorder=0)

                        #Plot line for r_mean
                        r_means_stimulus = r_mean_df.loc[condition][actor]
                        curr_ax.plot([grid_val_df[actor][condition], grid_val_df[actor][condition]+r_means_stimulus], [grid_aro_df[actor][condition], grid_aro_df[actor][condition]], color='red', linewidth=1.2, zorder=2)
                
                #Plot the points and the mean
                    curr_ax.scatter(xs, ys, color='black', alpha=0.8, s=5, zorder=1)
                    curr_ax.scatter(grid_val_df[actor][condition], grid_aro_df[actor][condition], color='red', s=9, alpha=0.9, zorder=2)


            #...and plot each individual distribution
            if save_figs:
                curr_ax.hlines(150, -150, 150, color='black', alpha=0.85, linewidth = 0.7)
                curr_ax.vlines(0, 0, 300, color='black', alpha=0.85, linewidth = 0.7)
                curr_ax.set_xlim([-150, 150])
                curr_ax.set_ylim([0, 300])
                curr_ax.set_xticks([])
                curr_ax.set_yticks([])
                curr_ax.spines['top'].set_visible(False)
                curr_ax.spines['right'].set_visible(False)
                curr_ax.spines['bottom'].set_visible(False)
                curr_ax.spines['left'].set_visible(False)
                min_max_score = "" #if actor == 'All means' else f" (CS={min_max_norm})"
                curr_ax.set_title(actor + min_max_score)

        #...finally, compute JSD and save for future figures
        jsd  = compute_jsd(np.array(all_cond_distributions))
        JSD_dict[condition] = round(jsd,2)

        #Plot
        if save_figs:
            plt.suptitle(condition, size=18) 
            plt.tight_layout()
            plt.savefig(f'figures/all_grid_plots/{condition}.png', dpi=100, bbox_inches='tight')
            plt.close()
            print("Saving figure:", f'figures/all_grid_plots/{condition}.png')

        #Save data for next time
        with open(JSD_data_path, "w") as file: 
            json.dump(JSD_dict, file)
    return JSD_dict

def compute_correlation_matrix(traits_df, correction_method=None):
    # Compute correlation matrix
    traits_corrs = traits_df.corr()

    n = traits_df.shape[1]
    corr_matrix = pd.DataFrame(np.eye(n), columns=traits_df.columns, index=traits_df.columns)
    p_matrix = pd.DataFrame(np.ones((n, n)), columns=traits_df.columns, index=traits_df.columns)

    # Compute upper triangle of correlation and p-value matrices
    for i, col1 in enumerate(traits_df.columns):
        for j, col2 in enumerate(traits_df.columns):
            if i < j:
                traits_df[col1] = pd.to_numeric(traits_df[col1], errors='coerce')
                traits_df[col2] = pd.to_numeric(traits_df[col2], errors='coerce')
                r, p = pearsonr(traits_df[col1], traits_df[col2])
                corr_matrix.iloc[i, j] = r
                corr_matrix.iloc[j, i] = r
                p_matrix.iloc[i, j] = p
                p_matrix.iloc[j, i] = p
    if correction_method is not None:
        # Flatten the upper triangle (excluding diagonal) for correction
        mask = np.triu(np.ones_like(p_matrix, dtype=bool), k=1)
        pvals_flat = p_matrix.where(mask).stack()

        # Holm-Bonferroni correction
        rej, pvals_corrected, _, _ = multipletests(pvals_flat.values, alpha=0.05, method=correction_method)

        # Reconstruct corrected p-value matrix
        corrected_p_matrix = pd.DataFrame(np.ones((n, n)), columns=traits_df.columns, index=traits_df.columns)
        corrected_p_matrix.values[mask] = pvals_corrected
        corrected_p_matrix = corrected_p_matrix.T.combine_first(corrected_p_matrix)  # Make symmetric
        np.fill_diagonal(corrected_p_matrix.values, np.nan)  # Diagonal = NaN
        p_matrix = corrected_p_matrix

    mask = np.triu(np.ones_like(traits_corrs, dtype=bool))
    masked_corrs = traits_corrs.mask(mask)
    p_matrix = p_matrix.mask(mask)
    #Plot the correlation matrix
    plt.figure(figsize=(12,12))
    ax = plt.gca()
    im = ax.imshow(masked_corrs, cmap='coolwarm', interpolation='none')
    #Only plot the upper triangle

    #Print number of significant correlations (ie < 0.05)
    significant_corrs = p_matrix[p_matrix < 0.05].count().sum()
    pprint(f'Number of significant correlations (p < 0.05): {significant_corrs}')
    column_names = [col.capitalize().replace('_', ' ') for col in traits_corrs.columns]
    plt.xticks(range(len(column_names)), column_names, rotation=45, ha='right')
    plt.yticks(range(len(column_names)), column_names)

    # Loop through correlation matrix to display correlation values and significance
    for i in range(len(traits_corrs.columns)):
        for j in range(len(traits_corrs.columns)):
          #  corr_value = traits_corrs.iloc[i, j]
            p_value = p_matrix.iloc[i, j]

            # Determine significance level
            if p_value < 0.001:
                stars = '***'
            elif p_value < 0.01:
                stars = '**'
            elif p_value < 0.05:
                stars = '*'
            else:
                stars = ''
            
            # Display the correlation value with significance stars
            plt.text(j, i, stars, ha='center', va='center', color="black")
    
    divider = make_axes_locatable(ax)
    cax = divider.append_axes("right", size="4%", pad=0.4)
    ax.grid(None)
    correction_label = 'uncorrected' if correction_method==None else 'corrected'
    fig_name = f'figures/actor-traits_correls_{correction_label}.png'
    plt.colorbar(im, cax=cax)
    plt.savefig(fig_name, dpi=150, bbox_inches='tight')
    plt.close()
    print('Saving figure:', fig_name)

# - - - 1-D MANIFOLD ANALYSIS - - -

def compute_isomap(data, n_components=1, n_neighbors=10):
    isomap = Isomap(n_components=n_components, n_neighbors=n_neighbors)
    embedding = isomap.fit_transform(data)
    eigenvalues = isomap.kernel_pca_.eigenvalues_
    explained_variance_ratio = eigenvalues / np.sum(eigenvalues)
    explained_variance_ratio = np.round(explained_variance_ratio, 3)

    #Get geodesic distances from the neutral point (closest to 0 in first component)
    pc1 = embedding[:, 0]
    neutral_index = np.argmin(np.abs(pc1))
    dist_from_neutral = isomap.dist_matrix_[neutral_index]

    return embedding, explained_variance_ratio, dist_from_neutral

def get_best_n_neighbors(grid_actor_df, n_components=5):
    best_NN = 0
    best_var = 0
    for n_NN in range(3,11):
        _, components_explained_variance, _ = compute_isomap(grid_actor_df, n_components=n_components, n_neighbors=n_NN)
        if components_explained_variance[0] > best_var:
            best_var = components_explained_variance[0]
            best_NN = n_NN
    return best_NN

# - - - PLOTTING - - - 

def my_heatmap(df, cmap, plot_title, png_title, fmt='.2g', save_plot=True):
    sns.set(font_scale=1)
    plt.figure(figsize=(10, 25))
    #Create gap between JSD values and min-max in JSD plot
    if png_title == 'grid/Min-max_norm_JSD_scores.png':
        df.insert(len(df.columns)-1, 'Empty', np.nan)
    g = sns.heatmap(df, 
                annot=True,
                annot_kws={'size': 8}, 
                cbar=True,
                cbar_kws={"shrink": 0.8, "aspect":60, "fraction":0.1},
                cmap=cmap,
                fmt=fmt)
    g.set_facecolor('xkcd:white')
    plt.title(plot_title, size=20)
    plt.xlabel('')
    plt.ylabel('')
    plt.tick_params(axis='both', 
                    which='both', 
                    pad=1,
                    length=5,
                    labelsize=10, 
                    labelbottom = False, 
                    bottom = False, 
                    top = True, 
                    labeltop=True)
    if png_title == 'grid/Min-max_norm_JSD_scores.png':
        try:
            plt.xticks(list(np.arange(0.5, 15.5,1)) + [16.5], np.insert(np.array(df.columns)[:-1], 0, np.array(['JSD'])))
        except:
            print('Ignoring label issue due to gap...')

    if save_plot:
        plt.savefig('figures/'+png_title, dpi=150, bbox_inches='tight')
        plt.close()
        print("Saving figure:", 'figures/'+png_title)

def my_heatmap_grays(df, df_asterisks, cmap, plot_title, png_title, save_plot=True):
    sns.set(font_scale=1)
    plt.figure(figsize=(10, 25))
    g = sns.heatmap(df, 
                annot=True,
                annot_kws={'size': 7}, 
                cbar=True,
                cbar_kws={"shrink": 0.8, "aspect":60, "fraction":0.1},
                cmap=cmap)
    g.set_facecolor('xkcd:white')
    plt.title(plot_title, size=15)
    plt.xlabel('')
    plt.ylabel('')
    plt.tick_params(axis='both', 
                    which='both', 
                    pad=1,
                    length=5,
                    labelsize=10, 
                    labelbottom = False, 
                    bottom = False, 
                    top = True, 
                    labeltop=True)
    
    # Manually change color of non-significant results to gray
    for i in range(df_asterisks.shape[0]):
        for j in range(df_asterisks.shape[1]):
            if not '*' in df_asterisks.values[i,j] and df_asterisks.values[i,j] != 'nan':
                plt.gca().add_patch(plt.Rectangle((j, i), 1, 1, fill=True, alpha=0.8, color='lightgray', linewidth=0.0))
    if save_plot:
        plt.savefig('figures/'+png_title, dpi=150, bbox_inches='tight')
        plt.close()
        print("Saving figure:", 'figures/'+png_title)

def plot_distributions(df, dim):
    plt.rcParams['grid.linewidth'] = 0.8
    fig, ax = plt.subplots(3,5, figsize=(14,8))
    sorted_cols = sorted(df.columns)
    xlim = [-130,120]
    if dim == 'Arousal':
        xlim = [70, 290]
    elif dim == 'Recognition accuracy':
        xlim = [0, 1]
    for i,col in enumerate(sorted_cols):
        color = 'cadetblue'
        ax[math.floor(i/5)][i%5].grid(True, zorder=0)
        if i == len(sorted_cols)-1:
            color = 'indianred'
            all_data = df[df.columns[:-1]].melt().value
            ax[math.floor(i/5)][i%5].hist(all_data, color=color, edgecolor='white', zorder=2)
            ax[math.floor(i/5)][i%5].set_title(dim)
            if dim == 'Recognition accuracy':
                #Dotted vline at 0.25
                ax[math.floor(i/5)][i%5].vlines(0.245, 0, 300, color='black', alpha=0.9, linewidth = 0.7, linestyle='--')
                ax[math.floor(i/5)][i%5].set_ylim([0, 250])
            mean = all_data.mean()
            std = all_data.std()
            median = all_data.median()
            print(f'{dim} mean: {mean}, std: {std}, median: {median}')
        else:
            ax[math.floor(i/5)][i%5].hist(df[col], color=color, edgecolor='white', zorder=2)
            ax[math.floor(i/5)][i%5].set_title(col)
        ax[math.floor(i/5)][i%5].set_xlim(xlim)
        #set tick size
        ax[math.floor(i/5)][i%5].tick_params(axis='both', which='both', pad=1, length=5, labelsize=7)

        plt.suptitle(f'{dim} score distributions', size=20)
    plt.tight_layout()
    dim = dim if ' ' not in dim else dim.replace(' ', '_')
    plt.savefig(f'figures/{dim}_distributions.png', dpi=150, bbox_inches='tight')
    plt.close()
    print("Saving figure:", f'figures/{dim}_distributions.png')
    plt.rcParams['grid.linewidth'] = 1.2         

def plot_scree_plot(components_explained_variance, n_components, actor, save_figure=True):
    plt.figure(figsize=(5, 3.5))
    plt.plot(range(1, n_components + 1), components_explained_variance, marker='o', color='indianred')
    plt.xlabel('Principal Component')
    plt.ylabel('Explained Variance (%)')
    plt.yticks(np.arange(0, 1.1, 0.1))
    plt.xticks(range(1, n_components + 1))
    plt.title(actor, size=15)
    plt.grid(False)
    plt.tight_layout()
    if save_figure:
        plt.savefig(f'figures/manifold/{actor}_screeplot.png', dpi=150, bbox_inches='tight')
        plt.close()
        print("Saving figure:",f'figures/manifold/{actor}_screeplot.png')
              
def non_overlapping_labels(grid_df, emotions, i):
    label_x = grid_df[0][i]+1
    label_y =  grid_df[1][i]+0.20
    addl_offset = -1.3
    #Modify x-axis
    if emotions[i] in []:
        label_x = grid_df[0][i]-5.7+addl_offset
    elif emotions[i] in [ 'Stern', '']:
        label_x =  grid_df[0][i]-6+addl_offset
    elif emotions[i] in ['Guilty','Baffled', 'Upset']:
        label_x =  grid_df[0][i]-7+addl_offset
    elif emotions[i] in ['Worried', 'Jealous', '', 'Uneasy']:
        label_x =  grid_df[0][i]-8+addl_offset
    elif emotions[i] in ['Amused', 'Dominant',  '']:
        label_x =  grid_df[0][i]-9+addl_offset
    elif emotions[i] in ['Accusing', 'Annoyed','Satisfied']:
        label_x =  grid_df[0][i]-10+addl_offset
    elif emotions[i] in [ 'Indifferent', '']:
        label_x =  grid_df[0][i]-10.5+addl_offset
    elif emotions[i] in [ 'Apologetic','Distrustful', 'Suspicious']:
        label_x =  grid_df[0][i]-12+addl_offset
    elif emotions[i] in ['Depressed','','Fantasizing', 'Concerned']: 
        label_x =  grid_df[0][i]-12.5+addl_offset
    elif emotions[i] in ['','Despondent']: 
        label_x =  grid_df[0][i]-14+addl_offset
    
    addl_offset = -0.3
    #Modify y-axis
    if emotions[i] in ['Guilty']:
        label_y =  grid_df[1][i]-0.28
    elif emotions[i] in ['Upset', '', 'Embarrassed', 'Assertive', 'Pensive', 'Defiant', 'Cautious', 'Doubtful', 'Embarrassed']:
        label_y =  grid_df[1][i]-0.25+addl_offset
    if emotions[i] in ['Irritated', 'Insulting', 'Relaxed',  'Thoughtful',
                    'Resentful', 'Dubious', 'Reflective', 'Contemplative']:
        label_y =  grid_df[1][i]-0.5+addl_offset
    elif emotions[i] in ['Tentative', 'Flustered','Concerned']:
        label_y =  grid_df[1][i]-1+addl_offset
    elif emotions[i] in [ 'Ashamed', 'Suspicious']:
        label_y =  grid_df[1][i]-1.3+addl_offset
    elif emotions[i] in [ 'Skeptical', 'Fantasizing','Satisfied','Dominant']:
        label_y =  grid_df[1][i]-1.8+addl_offset
    elif emotions[i] in ['Dominant', 'Worried', 'Uneasy','Sympathetic', 'Anxious','Impatient','Baffled']:
        label_y =  grid_df[1][i]+0.7
    elif emotions[i] in ['Indifferent']:
        label_y =  grid_df[1][i]+1.3
    return label_x, label_y

def plot_main_grid(grid_val_df, grid_aro_df, actor, coloring, cmap='viridis', colorbar_label='Position in First Isomap Component', title=None, save_figure=True):
    subject_plot = True if 'G' in actor else False
    main_fig = actor == 'MEAN'
    grid_df = np.array([grid_val_df[actor][:-1], grid_aro_df[actor][:-1]]).T
    grid_df = grid_df[~np.isnan(grid_df).any(axis=1)].T
    emotions=np.array(grid_val_df.index)[:-1]
 #   emotions = [conds_shortnames[em] if not main_fig else em for em in emotions]
    fig, ax_main = plt.subplots(figsize=(30, 18), dpi=80)

    #Plot stimuli labels ensuring non-overlap...
    all_label_coords = []
    for i in range(grid_df[0].shape[0]):
        
        #...manually for MEAN main figure
        if main_fig:
            label_x, label_y = non_overlapping_labels(grid_df, emotions, i)
            #Modify both axes and draw line connecting label to point
            if emotions[i] in ['Disappointed', 'Preoccupied', 'Regretful']:
                offset_x = 22
                offset_y = 3.5
                if emotions[i] == 'Disappointed':
                    offset_x = 28
                    offset_y = 5
                elif emotions[i] == 'Preoccupied':
                    offset_x = -10
                    offset_y = 5
                label_x =  grid_df[0][i]-offset_x
                label_y =  grid_df[1][i]-offset_y
                if emotions[i] == 'Disappointed':
                    ax_main.plot([label_x+16, label_x+offset_x], [label_y+1.5, label_y+offset_y], color='black', alpha=0.5)
                elif emotions[i] == 'Preoccupied':
                    ax_main.plot([label_x-0.5, label_x+offset_x], [label_y+1, label_y+offset_y], color='black', alpha=0.5)
                elif emotions[i] == 'Regretful':
                    ax_main.plot([label_x+11, label_x+offset_x], [label_y+1, label_y+offset_y], color='black', alpha=0.5)

        #...automatically for all actor figures
        else:
            label_x = grid_df[0][i]+1
            label_y =  grid_df[1][i]+0.20
            #While there's an overlap, modify x-axis
            threshold = 2.5
            overlap = True
            switched_left = False
            switched_down = False
            while overlap:
                overlap = False
                for coord in all_label_coords:
                    if abs(label_x - coord[0]) < threshold and abs(label_y - coord[1]) < threshold:
                        if not switched_left:
                            label_x -= 5
                            overlap = True
                            switched_left = True
                        elif not switched_down:
                        #    label_x += 5
                            label_y -= 3
                            overlap = True
                            switched_down = True
                            

            all_label_coords.append((label_x, label_y))

        ax_main.annotate(emotions[i], (label_x, label_y), color='black', size=16, zorder=4)

    #Main plot
    im = ax_main.scatter(grid_df[0], grid_df[1], c=coloring, cmap=cmap, s=180, alpha=0.9, zorder=3)
    ax_main.axhline(150, linewidth=1.3, color='black', alpha=0.5, zorder=2)
    ax_main.axvline(linewidth=1.3, color='black', alpha=0.5, zorder=2)

   # ax_main.set_ylim(110, 240)
    ax_main.grid(True, zorder=0)
    ax_main.set_xlabel('Valence', size=30)
    ax_main.set_ylabel('Arousal', size=30)
    ax_main.tick_params(labelsize=18)
    if main_fig:
        ax_main.axis('equal')
  #  ax_main.set_xlim(-90, 90)
    xlim = ax_main.get_xlim()
    xticks = np.arange(np.floor(xlim[0] / 20) * 20, np.ceil(xlim[1] / 20) * 20 + 1, 20)
    ax_main.set_xticks(xticks)
    y_lim = ax_main.get_ylim()
    yticks = np.arange(np.floor(y_lim[0] / 20) * 20, np.ceil(y_lim[1] / 20) * 20 + 1, 20)
    ax_main.set_yticks(yticks)
    if title is not None:
        ax_main.set_title(title, size=50)

    #Small corner plot
    ax_inset = inset_axes(ax_main, width="20%", height="30%", loc='lower right')
    ax_inset.scatter(grid_df[0], grid_df[1], c=coloring, cmap=cmap, s=100, zorder=3)
    ax_inset.set_xticks([])
    ax_inset.set_yticks([])
    ax_inset.set_ylim([0, 300])
    ax_inset.set_xlim([-150, 150])
    ax_inset.axhline(150, linewidth=3, color='black', zorder=0)
    ax_inset.axvline(linewidth=3, color='black', zorder=1)
    ax_inset.spines['top'].set_linewidth(1.5)
    ax_inset.spines['right'].set_linewidth(3)
    ax_inset.spines['bottom'].set_linewidth(3)
    ax_inset.spines['left'].set_linewidth(1.5)

    #Colorbar
    divider = make_axes_locatable(ax_main)
    cax = divider.append_axes('right', size='3%', pad=0.5)
    colorbar = fig.colorbar(im, cax=cax, orientation='vertical')
    colorbar.ax.tick_params(labelsize=18)  # Increase tick font size
    colorbar.set_label(colorbar_label, fontsize=25)

    #Save figure
    if save_figure is True:
        saving_direc = 'figures/manifold/main_gridplot.png'
        sub_dir = 'subjects' if subject_plot else 'actors'
        plt.savefig(saving_direc, dpi=150, bbox_inches='tight')
        plt.close()
        print("Saving figure:",saving_direc)

def plot_mini_grid(grid_val_df, grid_aro_df, col, coloring, cmap='viridis', colorbar_label=None, 
                   title=None, save_figure=True, var='', normalized_grid=''):
    
    if 'G' in col:                      #Subject selection
        grid_df = np.array([grid_val_df[col], grid_aro_df[col]]).T
    elif 'F' in col or 'M' in col:      #Actor selection
        grid_df = np.array([grid_val_df[col], grid_aro_df[col]]).T
    elif col == 'all' or col is None:   #All data selection
        grid_df = np.array([grid_val_df, grid_aro_df]).T
    else:
        raise ValueError(f"Invalid column selection: {col}. Must be actor, subject, or 'all' / None.")
    grid_df = grid_df[~np.isnan(grid_df).any(axis=1)].T
    coloring = coloring[~np.isnan(grid_df).any(axis=0)]

    if colorbar_label is not None:
        plt.figure(figsize=(9, 7), dpi=80)
    else:
        plt.figure(figsize=(7, 7), dpi=80)
    dps_size = 120 if len(coloring) < 100 else 20
    if cmap == 'categorical':
        cmap = sns.color_palette("Set1", n_colors=len(np.unique(coloring)))
        coloring = [cmap[int(i)] for i in coloring]
        plt.scatter(grid_df[0,:], grid_df[1,:], c=coloring, s=dps_size, zorder=1)
    else:
        plt.scatter(grid_df[0,:], grid_df[1,:], c=coloring, cmap=cmap, s=dps_size, zorder=1)
    plt.axis('equal')
    plt.xticks([])
    plt.yticks([])
    if normalized_grid:
        plt.ylim([-5,5])
        plt.xlim([-5,5])
        plt.axhline(linewidth=3, color='black', zorder=0)
    else:
        plt.ylim([0, 300])
        plt.xlim([-150, 150])
        plt.axhline(150, linewidth=3, color='black', zorder=0)
    plt.axvline(linewidth=3, color='black', zorder=1)
    if title is not None:
        plt.title(title, size=24)
    if colorbar_label is not None:
        cbar = plt.colorbar()
        
        cbar.ax.tick_params(labelsize=18)
        cbar.set_label(colorbar_label, size=19)
    
    #Save or show figure
    if save_figure is True:
        saving_direc = f'figures/manifold/{var}.png'
        plt.savefig(saving_direc, dpi=150, bbox_inches='tight')
        plt.close()
        print("Saving figure:",saving_direc)

